# Generated by Django 3.1.4 on 2020-12-04 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
        migrations.RenameModel(
            old_name='Reviewers',
            new_name='Reviewer',
        ),
        migrations.CreateModel(
            name='Expectation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('TRA', 'Trainee'), ('JUN', 'Junior'), ('MID', 'Middle'), ('SEN', 'Senior')], max_length=3)),
                ('description', models.TextField()),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.criteria')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(0, 'No data to decide'), (1, 'Way below expectations'), (2, 'Below expectations'), (3, 'Meet expectations'), (4, 'Above expectations'), (5, 'Way above expectations')])),
                ('comment', models.TextField()),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.criteria')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.review')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.reviewer')),
            ],
        ),
    ]
