# Generated by Django 3.1.4 on 2020-12-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20201204_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('TRA', 'Trainee'), ('JUN', 'Junior'), ('MID', 'Middle'), ('SEN', 'Senior')], max_length=3, null=True),
        ),
    ]
